---
abstract: 'Make serving static pages painless.'
author:
  - 'Andy Grundman, <andy@hybridized.org>'
build_requires:
  ExtUtils::MakeMaker: 6.36
  Test::More: 0
  Test::Pod: 1.14
  Test::Pod::Coverage: 1.04
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-Plugin-Static-Simple-ButMaintained
no_index:
  directory:
    - inc
    - t
requires:
  Catalyst::Runtime: 5.80008
  MIME::Types: 1.25
  Moose: 0
  MooseX::Types: 0
  Test::More: 0
  namespace::autoclean: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/EvanCarroll/Catalyst-Plugin-Static-Simple.git
version: 0.30
